# Site settings
title: Ben's Blog
email: benb88@gmail.com
description: "tech life with passion"
baseurl: ""
url: "http://blog.bencao.it"
username: bencao
fullname: Ben Cao

# Build settings
markdown: kramdown
permalink: pretty

kramdown:
  input: GFM
